repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.0.0
    hooks:
    -   id: seed-isort-config
        stages: [manual]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
        stages: [manual]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    files: "*.py"
    hooks:
    - id: black
      language_version: python3.7
      args: [--safe]

default_language_version:
    python: python3.7
